### ISSUE TITLE
fix tests

### ISSUE THREAD

**Issue by hughrun** [bookwyrm-social/bw-file-resubmit#3]
**Describe the bug**
The admin-resave tests are failing with a weird error. As far as I can tell everything _actually_ works, and these tests also fail on the `django-file-resubmit` codebase.

**To Reproduce**
1. run tests using pytest
2. see that two fail with an error

**Expected behavior**
all tests pass

**Additional context**
I think it may be something to do with django not being installed in `requirements.txt`, and it looks a bit like a migrations error.

---

**System details (please complete the following information):**
    - OS: [e.g. MacOS]
    - Django Version [e.g. 3.2.2]
    - bw-file-resubmit Version [e.g. 0.6.0]

**Comment by hughrun** [comment]
The error in both cases is `django.db.utils.IntegrityError: The row in table 'django_admin_log' with primary key '1' has an invalid foreign key: django_admin_log.content_type_id contains a value '6' that does not have a corresponding value in django_content_type.id.`

@mouse-reeve any idea here? It's either a bug in `AdminResubmitMixin` or, more likely, a bug in the tests. My web searching skills aren't coming up with any answers I can understand.

**Comment by mouse-reeve** [comment]
Okay this is unhinged, but I did get the test to pass. As far as I can tell, the django admin panel creates log entries that note every action taken from the admin panel. This part I don't know, but my guess is that the internal Django code completes some part of that in a signal listener or similar that isn't executed during the tests. So when the test tries to run a command via the admin panel, django tries to log it, and then is unable to create a content type foreign key, and fails. I looked at the django codebase and figure out [where they are creating those entries](https://github.com/django/django/blob/535f7b5c6cea54a0796d85bbe213183d50002689/tests/admin_utils/models.py#L95), and was able to mock that function:

``` python
from unittest.mock import patch

...
def test_image_resubmit_save_admin(self):
...
        with patch("django.contrib.admin.models.LogEntryManager.log_action"):
            saved_obj = testadmin.add_view(resubmit_req)  # <=== BUG here
```

And the test now passes

**Comment by mouse-reeve** [comment]
Well shoot I pushed it directly to main instead of making a PR, undermining how much of a _total genius_ I was giving myself credit for being, but this should be fixed by https://github.com/bookwyrm-social/bw-file-resubmit/commit/d7f6fd6089a9c79387af6281ddd13af1f11f7ad2

**Comment by hughrun** [comment]
I'm impressed!
